<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Game_Library</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Fonts\SF-Pro.ttf" />
    <None Remove="Resources\IMG_1067_500.jpg" />
    <None Remove="Resources\IMG_1079_500.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\IMG_1067_500.jpg" />
    <Resource Include="Resources\IMG_1079_500.jpg" />
    <Resource Include="Resources\Thumbnail-Placeholder.jpg" />
    <Resource Include="Resources\Fonts\SF-Pro.ttf" />
  </ItemGroup>

</Project>
